// src/dts.ts
export function createDts(permissions: string[], typeName = 'PermissionKey') {
  if (permissions.length === 0) {
    return `export type ${typeName} = string\n`
  }

  const union = permissions.map((item) => `  | ${JSON.stringify(item)}`).join('\n')

  return [
    '/* eslint-disable */',
    '// This file is generated by vite-plugin-permission.',
    '// Do not edit manually.',
    '',
    `export type ${typeName} =`,
    union,
    ''
  ].join('\n')
}
