// src/dts.ts
export function createDts(permissions: string[], typeName = 'PermissionKey') {
  const uniquePermissions = [...new Set(permissions)].sort((left, right) =>
    left.localeCompare(right)
  )

  const permissionKeysType =
    uniquePermissions.length > 0
      ? `readonly [${uniquePermissions.map((item) => JSON.stringify(item)).join(', ')}]`
      : 'readonly string[]'

  return [
    '/* eslint-disable */',
    '// This file is generated by vite-plugin-permission.',
    '// Do not edit manually.',
    '',
    `export declare const permissionKeys: ${permissionKeysType}`,
    `export type ${typeName} = typeof permissionKeys[number]`,
    '',
    `export type PermissionUsage = {`,
    `  permission: ${typeName}`,
    '  file: string',
    '  line?: number',
    '  column?: number',
    '  component?: string',
    '}',
    '',
    `export type PermissionManifestEntry = {`,
    `  permission: ${typeName}`,
    '  count: number',
    '  files: readonly string[]',
    '  usages: readonly PermissionUsage[]',
    '}',
    '',
    'export type PermissionManifestSummary = {',
    '  permissions: number',
    '  usages: number',
    '  files: number',
    '}',
    '',
    'export type PermissionManifest = {',
    '  generatedAt: string',
    '  summary: PermissionManifestSummary',
    '  permissions: readonly PermissionManifestEntry[]',
    '}',
    ''
  ].join('\n')
}
