import { parse } from '@babel/parser'
import traverse from '@babel/traverse'
import type {
  JSXAttribute,
  JSXIdentifier,
  JSXMemberExpression,
  JSXNamespacedName
} from '@babel/types'
import fs from 'node:fs/promises'
import path from 'node:path'
import fg from 'fast-glob'

export type PermissionUsage = {
  permission: string
  file: string
  line?: number
  column?: number
  component?: string
}

export type PermissionManifestEntry = {
  permission: string
  count: number
  files: string[]
  usages: Array<Pick<PermissionUsage, 'file' | 'line' | 'column' | 'component'>>
}

export type PermissionManifest = {
  generatedAt: string
  summary: {
    permissions: number
    usages: number
    files: number
  }
  permissions: PermissionManifestEntry[]
}

export type ScanProjectOptions = {
  cwd: string
  include?: string[]
  exclude?: string[]
  attributes?: string[]
}

const DEFAULT_INCLUDE = ['src/**/*.{ts,tsx,jsx}']
const DEFAULT_EXCLUDE = [
  '**/node_modules/**',
  '**/dist/**',
  '**/.vite/**',
  '**/.turbo/**',
  '**/*.test.*',
  '**/*.spec.*',
  '**/*.stories.*'
]

export async function scanProject(options: ScanProjectOptions) {
  const include = options.include?.length ? options.include : DEFAULT_INCLUDE
  const exclude = options.exclude?.length ? options.exclude : DEFAULT_EXCLUDE
  const attributes = new Set(options.attributes?.length ? options.attributes : ['permission'])
  const files = await fg(include, {
    cwd: options.cwd,
    absolute: true,
    onlyFiles: true,
    ignore: exclude
  })

  const usages: PermissionUsage[] = []

  for (const file of files) {
    const code = await fs.readFile(file, 'utf-8')
    usages.push(...scanFile(code, file, attributes))
  }

  return buildManifest(usages)
}

export function buildManifest(usages: PermissionUsage[]): PermissionManifest {
  const grouped = new Map<string, PermissionUsage[]>()

  for (const usage of usages) {
    const items = grouped.get(usage.permission) ?? []
    items.push(usage)
    grouped.set(usage.permission, items)
  }

  const sortedPermissions = [...grouped.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([permission, entries]) => {
      const sortedEntries = [...entries].sort((left, right) => compareUsage(left, right))
      const files = [...new Set(sortedEntries.map((item) => item.file))].sort((left, right) =>
        left.localeCompare(right)
      )

      return {
        permission,
        count: sortedEntries.length,
        files,
        usages: sortedEntries.map(({ file, line, column, component }) => {
          const entry: PermissionManifestEntry['usages'][number] = { file }

          if (line !== undefined) {
            entry.line = line
          }

          if (column !== undefined) {
            entry.column = column
          }

          if (component !== undefined) {
            entry.component = component
          }

          return entry
        })
      }
    })

  return {
    generatedAt: new Date().toISOString(),
    summary: {
      permissions: new Set(usages.map((item) => item.permission)).size,
      usages: usages.length,
      files: new Set(usages.map((item) => item.file)).size
    },
    permissions: sortedPermissions
  }
}

export function collectPermissions(manifest: PermissionManifest) {
  return manifest.permissions.map((item) => item.permission)
}

export function createDts(permissions: string[], typeName = 'PermissionKey') {
  const uniquePermissions = [...new Set(permissions)].sort((left, right) =>
    left.localeCompare(right)
  )

  const permissionKeysType =
    uniquePermissions.length > 0
      ? `readonly [${uniquePermissions.map((item) => JSON.stringify(item)).join(', ')}]`
      : 'readonly string[]'

  return [
    '/* eslint-disable */',
    '// This file is generated by permission-kit cli.',
    '// Do not edit manually.',
    '',
    `export declare const permissionKeys: ${permissionKeysType}`,
    `export type ${typeName} = typeof permissionKeys[number]`,
    '',
    `export type PermissionUsage = {`,
    `  permission: ${typeName}`,
    '  file: string',
    '  line?: number',
    '  column?: number',
    '  component?: string',
    '}',
    '',
    `export type PermissionManifestEntry = {`,
    `  permission: ${typeName}`,
    '  count: number',
    '  files: readonly string[]',
    '  usages: readonly PermissionUsage[]',
    '}',
    '',
    'export type PermissionManifestSummary = {',
    '  permissions: number',
    '  usages: number',
    '  files: number',
    '}',
    '',
    'export type PermissionManifest = {',
    '  generatedAt: string',
    '  summary: PermissionManifestSummary',
    '  permissions: readonly PermissionManifestEntry[]',
    '}',
    ''
  ].join('\n')
}

function scanFile(code: string, file: string, attributes: Set<string>) {
  if (!/\.[jt]sx$/.test(file)) {
    return []
  }

  const ast = parse(code, {
    sourceType: 'module',
    plugins: ['jsx', 'typescript'],
    errorRecovery: true
  })

  const usages: PermissionUsage[] = []

  traverse(ast, {
    JSXElement(path) {
      const node = path.node
      const openingName = node.openingElement.name

      if (openingName.type === 'JSXIdentifier' && openingName.name === 'Can') {
        return
      }

      const permissionAttr = node.openingElement.attributes.find((attr): attr is JSXAttribute => {
        return (
          attr.type === 'JSXAttribute' &&
          attr.name.type === 'JSXIdentifier' &&
          attributes.has(attr.name.name)
        )
      })

      if (!permissionAttr) {
        return
      }

      const permission = getStaticStringValue(permissionAttr)
      if (!permission) {
        return
      }

      const usage: PermissionUsage = {
        permission,
        file: normalizeFilePath(file),
        component: getJSXName(node.openingElement.name)
      }

      if (permissionAttr.loc?.start.line !== undefined) {
        usage.line = permissionAttr.loc.start.line
      }

      if (permissionAttr.loc?.start.column !== undefined) {
        usage.column = permissionAttr.loc.start.column
      }

      usages.push(usage)
    }
  })

  return usages
}

function getStaticStringValue(attr: JSXAttribute) {
  const value = attr.value

  if (!value) {
    return null
  }

  if (value.type === 'StringLiteral') {
    return value.value
  }

  if (value.type === 'JSXExpressionContainer' && value.expression.type === 'StringLiteral') {
    return value.expression.value
  }

  return null
}

function getJSXName(name: JSXIdentifier | JSXMemberExpression | JSXNamespacedName): string {
  if (name.type === 'JSXIdentifier') {
    return name.name
  }

  if (name.type === 'JSXMemberExpression') {
    return `${getJSXName(name.object)}.${getJSXName(name.property)}`
  }

  return `${name.namespace.name}:${name.name.name}`
}

function normalizeFilePath(file: string) {
  return file.split(path.sep).join('/')
}

function compareUsage(left: PermissionUsage, right: PermissionUsage) {
  const fileCompare = left.file.localeCompare(right.file)
  if (fileCompare !== 0) {
    return fileCompare
  }

  const lineCompare = (left.line ?? 0) - (right.line ?? 0)
  if (lineCompare !== 0) {
    return lineCompare
  }

  const columnCompare = (left.column ?? 0) - (right.column ?? 0)
  if (columnCompare !== 0) {
    return columnCompare
  }

  return (left.component ?? '').localeCompare(right.component ?? '')
}
